#version 460 core
#define MAX_RAY 4
#define PI 3.1415926535897932384626433832795
layout(local_size_x = 8, local_size_y = 8) in;

layout(rgba32f, binding = 0) uniform image2D imgOutput;

layout(rgba8, binding = 1) uniform image2D skyboxtex;

uniform mat4 projection;
uniform mat4 view;
uniform mat4 invView;
uniform vec2 u_resolution;
uniform vec2 sky_resolution;
uniform int frame;
uniform int meshcount;

float fov = 60.0;

const float epsilon = 0.0001;
// ivec2 pixel;

// number of triangles, color, reflectance, triangles...
#define CIRCLE_STRIDE 8

// layout(std430, binding = 0) buffer DataBuffer {
//     float boundingcontent[];
// };

layout(std430, binding = 0) buffer DataBuffer {
    float values[];
};

layout(std430, binding = 1) buffer DataBuffer2 {
    float light[];
};

layout(std430, binding = 2) buffer DataBuffer3 {
    float circles[];
};

layout(std430, binding = 3) buffer DataBuffer4 {
    float boundings[];
};
// vec3 point_light = vec3(2, -10, 0);
// float h.reflectiveness = 2.5;
// vec3 light_color = vec3(1,1,1);

// pos, h.reflectiveness, color
// float light[] = float[](2, -10, 0, 2.5, 0, 1, 1, -2, -10, 0, 2.5, 1, 1, 0);

vec3 ground = vec3(0, -1, 0);
vec3 ground_point = vec3(-1, 1.0, -7.0);
struct Circle {
    vec3 pos;
    float radius;
    vec4 color;
    float reflectance;
};


// #define MAX_CIRCLES 4
// Circle circles[MAX_CIRCLES] = Circle[](
//     Circle(vec3(0,-2,-3), 1.0, vec4(1,0,0,1)),
//     Circle(vec3(0,-2,-5), 2.0, vec4(1,1,0,1)),
//     Circle(vec3(0,0,-10), 2.5, vec4(1,1,1,1)),
//     Circle(vec3(-1, -2.0, -7), 1, vec4(1,1,1,1))
//     // Circle(vec3(0,50,-7), 50.0, vec4(0.5,0.5,0.0,1.0))
// );

struct HitInfo {
    bool hit;
    vec4 col;
    vec3 normal;
    float t;
    int idx;
    float reflectiveness;
};

bool intersectSphere(vec3 ro, vec3 rd, Circle c, out float tHit) {
    // c.pos = (view * vec4(c.pos, 1.0)).xyz; // Transform circle position to view space
    vec3 oc = ro - c.pos;//(view * vec4(c.pos, 1.0)).xyz;
    float a = dot(rd, rd);
    float b = 2.0 * dot(oc, rd);
    float cc = dot(oc, oc) - c.radius*c.radius;
    float disc = b*b - 4.0*a*cc;
    if(disc < 0.0) return false;
    float t0 = (-b - sqrt(disc)) / (2.0*a);
    float t1 = (-b + sqrt(disc)) / (2.0*a);
    tHit = (t0 > 0.0) ? t0 : ((t1 > 0.0) ? t1 : -1.0);
    return tHit > 0.0;
}

vec3 skybox(vec3 rdir){
    // return vec3(0);
    vec3 dir = vec3(rdir.x + cos(0)*sin(frame*0.01), rdir.y + sin(0)*sin(frame*0.01), rdir.z + cos(frame*0.01));
    vec3 rd = rdir;//normalize((invView * vec4(rdir,0.0)).xyz); // Transform ray direction to view space
    
    ivec2 pixel = ivec2(int((atan(rd.z, rd.x) / (2.0 * PI) + 0.5) * sky_resolution.x), int((asin(clamp(rd.y, -1.0, 1.0)) / PI + 0.5) * sky_resolution.y));
    pixel.y = int(sky_resolution.y) - pixel.y - 1; // Flip Y for image lookup
    pixel = clamp(pixel, ivec2(0), ivec2(sky_resolution.x, sky_resolution.y) - 1);
    return clamp(imageLoad(skyboxtex, pixel).xyz, 0.0, 1.0);
    // return vec3((sky_resolution.x)/1200, (sky_resolution.y), 0.0); // Debug: visualize UV coords
    // return clamp(imageLoad(skyboxtex, ivec2(1,1)), 0.0, 1.0);
}

bool intersectTriangle(vec3 ro, vec3 rd, vec3 v0, vec3 v1, vec3 v2, vec3 n0, vec3 n1, vec3 n2, out float t, out vec3 normal, int hasnormal) {

    // v0 = (view * vec4(v0, 1.0)).xyz; // Transform triangle vertices to view space
    // v1 = (view * vec4(v1, 1.0)).xyz;
    // v2 = (view * vec4(v2, 1.0)).xyz;

    vec3 edge1 = v1 - v0;
    vec3 edge2 = v2 - v0;
    vec3 edge3 = v2 - v1;
    normal = normalize(cross(edge1, edge2));
    
    if(hasnormal == 0 && dot(normal, rd) > 0.0) {
        normal = -normal; // Ensure normal faces against ray
    }

    float det = dot(rd,normal);
    if (abs(det) < 1e-4) return false; // Ray is parallel to triangle
    
    t = dot(v0 - ro, normal) / det;
    vec3 hitPoint = ro + rd * t;


    float area = length(cross(edge1, edge2))*0.5;
    float a1 = length(cross(v1 - v0, hitPoint - v0))*0.5;
    float a2 = length(cross(v2 - v1, hitPoint - v1))*0.5;
    float a3 = length(cross(v0 - v2, hitPoint - v2))*0.5;
    float areapoint = a1 + a2 + a3;
    if (abs(area - areapoint) > 1e-4) return false;

    if (hasnormal == 1){
        normal = (n0 * (a2/areapoint) + n1 * (a3/areapoint) + n2 * (a1/areapoint));
    }

    return t > 0.0;
}

bool intersectBoundingBox(vec3 o, vec3 dim, vec3 ro, vec3 rd){
    if (rd.x == 0){
        rd.x = 1e-5;
    }
    if (rd.y == 0){
        rd.y = 1e-5;
    }
    if (rd.z == 0){
        rd.z = 1e-5;
    }
    vec3 tmin = (ro - o)/rd;
    vec3 tmax = (ro -(o+dim))/rd;
    float tm = max(tmin.x,max(tmin.y,tmin.z));
    float tmx = min(tmax.x, min(tmax.y,tmax.z));

    return (tmx) <= (tm);
    // return true;
}

HitInfo getHit(vec3 ro, vec3 rd, bool groundIntersect, float tl) {
    HitInfo h;
    // h.col = vec4(0,0,0,1);
    h.col = vec4(skybox(rd),1.0);
    h.t = 1e9;
    h.idx = -1;
    h.hit = false;
    h.reflectiveness = 0.0;

    float t;
    
    // int stack[1024];
    // int stackptr = 0;
    // stack[stackptr++] = 0;

    // while (stackptr > 0){
    //     int current = stack[--stackptr];
    //     // if (visited[current] == 21){
    //     //     continue;
    //     // }else {
    //     //     visited[current] = 21;
    //     // }
    //     vec3 orig = vec3(boundings[current*10+2],boundings[current*10+3],boundings[current*10+4]);
    //     vec3 dim =  vec3(boundings[current*10+5],boundings[current*10+6],boundings[current*10+7]);
    //     if(!intersectBoundingBox(orig,dim,ro,rd)){
    //         continue;
    //     }
    //     int c1 = int(boundings[current*10 + 8]);
    //     int c2 = int(boundings[current*10 + 9]);
        
    //     int isleaf = int(boundings[current*10 + 1]);
    //     if (isleaf == 1){
    //         //leaf
    //         int mc = int(boundingcontent[int(boundings[current*10])]);
    //         if(mc == 0){
    //             continue;
    //         }
    //         int id = int(boundings[current*10])+1;
    //         for(int j = 0; j<mc; j++){
    //             vec4 meshcol = vec4(boundingcontent[id+1],boundingcontent[id+2],boundingcontent[id+3],1.0);
    //             float reflectance = boundingcontent[id+4];
    //             int numtriangles = int(boundingcontent[id+0]);

    //             for(int i = 0; i<numtriangles; i++){
    //                 vec3 v0 = vec3(boundingcontent[id+5 + i*9 + 0], boundingcontent[id+5 + i*9 + 1], boundingcontent[id+5 + i*9 + 2]);
    //                 vec3 v1 = vec3(boundingcontent[id+5 + i*9 + 3], boundingcontent[id+5 + i*9 + 4], boundingcontent[id+5 + i*9 + 5]);
    //                 vec3 v2 = vec3(boundingcontent[id+5 + i*9 + 6], boundingcontent[id+5 + i*9 + 7], boundingcontent[id+5 + i*9 + 8]);
    //                 vec3 normal;

    //                 if(intersectTriangle(ro, rd, v0, v1, v2, t, normal) && t>0.001 && t < h.t) {
    //                     h.hit = true;
    //                     h.t = t;
    //                     h.col = meshcol;
    //                     h.idx = j+i;
    //                     if (reflectance > 1.0){
    //                         h.idx = -2;
    //                     }
    //                     h.reflectiveness = reflectance;
    //                     h.normal = normal;
    //                 }
    //             }
    //             id += 5 + numtriangles*9;
    //         }

    //         if(h.hit){
    //             break;
    //         }


    //     }else {

    //         vec3 orig = vec3(boundings[c1*10+2],boundings[c1*10+3],boundings[c1*10+4]);
    //         vec3 dim =  vec3(boundings[c1*10+5],boundings[c1*10+6],boundings[c1*10+7]);
    //         vec3 centr = orig+ dim/2;
    //         float l1 = length(centr - ro);

    //         vec3 orig2 = vec3(boundings[c2*10+2],boundings[c2*10+3],boundings[c2*10+4]);
    //         vec3 dim2 =  vec3(boundings[c2*10+5],boundings[c2*10+6],boundings[c2*10+7]);
    //         vec3 centr2 = orig2+ dim2/2;
    //         float l2 = length(centr2 - ro);
            
    //         if (l2 > l1){
    //             stack[stackptr++] = c2;
    //             stack[stackptr++] = c1;
    //         }else {
    //             stack[stackptr++] = c1;
    //             stack[stackptr++] = c2;
    //         }
    //     }
    // }

    int idx = 0;

    for(int j = 0; j<meshcount; j++){
        vec4 meshcol = vec4(values[idx+1],values[idx+2],values[idx+3],1.0);
        // meshcol = vec4(1);
        float reflectance = values[idx+4];
        int hasnormal = int(values[idx+5]);
        int numtriangles = int(values[idx+0]);
        int multiplier = 9;
        if (hasnormal == 1){
            multiplier = 18;
        }
        for(int i = 0; i<numtriangles; i++){
            vec3 v0 = vec3(values[idx+6 + i*multiplier + 0], values[idx+6 + i*multiplier + 1], values[idx+6 + i*multiplier + 2]);
            vec3 v1 = vec3(values[idx+6 + i*multiplier + 3], values[idx+6 + i*multiplier + 4], values[idx+6 + i*multiplier + 5]);
            vec3 v2 = vec3(values[idx+6 + i*multiplier + 6], values[idx+6 + i*multiplier + 7], values[idx+6 + i*multiplier + 8]);

            vec3 n0,n1,n2;
            
            if(hasnormal == 1){
                n0 = vec3(values[idx+6 + i*multiplier + 9], values[idx+6 + i*multiplier + 10], values[idx+6 + i*multiplier + 11]);
                n1 = vec3(values[idx+6 + i*multiplier + 12], values[idx+6 + i*multiplier + 13], values[idx+6 + i*multiplier + 14]);
                n2 = vec3(values[idx+6 + i*multiplier + 15], values[idx+6 + i*multiplier + 16], values[idx+6 + i*multiplier + 17]);
            }else {
                n0 = vec3(0);
                n1 = vec3(0);
                n2 = vec3(0);
            }
            vec3 normal;

            if(intersectTriangle(ro, rd, v0, v1, v2, n0,n1,n2, t, normal, hasnormal) && t>0.001 && t < h.t) {
                h.hit = true;
                h.t = t;
                h.col = meshcol;
                h.idx = j+i;
                if (reflectance > 1.0){
                    h.idx = -2;
                }
                h.reflectiveness = reflectance;
                h.normal = normal;
            }
        }
        idx += 6 + numtriangles*9;
    }

    for(int i=0; i<circles.length()/CIRCLE_STRIDE; i++) {
        Circle circle = Circle(
            vec3(circles[i*CIRCLE_STRIDE + 0], circles[i*CIRCLE_STRIDE + 1], circles[i*CIRCLE_STRIDE + 2]),
            circles[i*CIRCLE_STRIDE + 3],
            vec4(circles[i*CIRCLE_STRIDE + 4], circles[i*CIRCLE_STRIDE + 5], circles[i*CIRCLE_STRIDE + 6], 1.0),
            circles[i*CIRCLE_STRIDE + 7]
        );
        if(intersectSphere(ro, rd, circle, t) && t < h.t && t > 0.0) {
            h.hit = true;
            h.t = t;
            h.col = circle.color;
            h.idx = i;
            h.reflectiveness = circle.reflectance;
            vec3 oc = circle.pos;//(view * vec4(circle.pos, 1.0)).xyz;
            vec3 hitpoint = ro + rd * h.t;
            h.normal = normalize(hitpoint - oc);
        }
    }

    for(int i=0; i<light.length()/CIRCLE_STRIDE; i++) {
        Circle circle = Circle(
            vec3(light[i*CIRCLE_STRIDE + 0], light[i*CIRCLE_STRIDE + 1], light[i*CIRCLE_STRIDE + 2]),
            light[i*CIRCLE_STRIDE + 7],
            vec4(light[i*CIRCLE_STRIDE + 4], light[i*CIRCLE_STRIDE + 5], light[i*CIRCLE_STRIDE + 6], 1.0),
            light[i*CIRCLE_STRIDE + 3]
        );
        if(intersectSphere(ro, rd, circle, t) && t < h.t && t > 0.0) {
            h.hit = true;
            h.t = t;
            h.col = circle.color;
            h.idx = -2;
            h.reflectiveness = circle.reflectance;
            vec3 oc = circle.pos;//(view * vec4(circle.pos, 1.0)).xyz;
            vec3 hitpoint = ro + rd * h.t;
            h.normal = normalize(hitpoint - oc);
        }
    }


    if(groundIntersect){
        h.hit = true;
        h.reflectiveness = 1.0;
        float t_ground = dot(ground,ground_point-ro)/ dot(ground, rd);
        vec3 groundhit = ro + rd * t_ground;
        if(length(groundhit) < h.t && groundhit.z < 0.0){
            h.t = length(groundhit);
            float color = 1- clamp(length(groundhit)/200.0, 0.0, 1.0);
            h.col = vec4(0.5, 0.5, 0.0,color); // Ground color
            h.idx = -1; // No circle hit
            h.normal = ground;
        }
    }
    return h;
}

float rand(vec2 co)
{
    return fract(sin(dot(co.xy ,vec2(12.9898,78.233))) * 43758.5453);
}

// uint hash(uint x) {
//     x ^= x >> 16;
//     x *= 0x7feb352dU;
//     x ^= x >> 15;
//     x *= 0x846ca68bU;
//     x ^= x >> 16;
//     return x;
// }

// Convert the uint hash to a float in range [0, 1]
// float rand(vec2 co) {
//     uint x = floatBitsToUint(co.x + co.y);
//     return float(hash(x)) / float(0xffffffffU);
// }

vec4 diffuse(vec3 origin, vec3 n, int selfidx, ivec2 sampl, ivec2 pixel, int nbounces) {
    // Build TBN basis aligned to surface normal
    vec3 up = abs(n.y) < 0.999 ? vec3(0,1,0) : vec3(1,0,0);
    vec3 tangent   = normalize(cross(up, n));
    vec3 bitangent = cross(n, tangent);

    float golden_angle = PI * (3.0 - sqrt(5.0)); // correct golden angle in radians
    int n_points = 5;
    int nn = 0;
    vec4 return_color = vec4(0);
    // int idx = frame*200;
    // for (int i = idx%n_points; i < min((idx%n_points)+200,n_points); i++) {
    for (int i = 0; i < n_points; i++) {
        // Generate hemisphere sample in local space

        // for(int j = 0; j<1; j++){
            // int i = (int(random(uint(frame+j))*n_points ));
            vec3 ro = vec3(origin);
            float prevt = -10.0;
            vec4 retcolor = vec4(0);
            float reflectivity = 1.0;
            for (int j = 0; j < nbounces; j++) {
                float theta = rand(vec2(float(i+frame+pixel.x+pixel.y + ro.x), float(ro.y+ro.z + sampl.x+sampl.y+frame)));
                float phi = rand(vec2(float(ro.y+ro.z + sampl.x+sampl.y+frame),float(i+frame+pixel.x+pixel.y + ro.x)))*2*PI;

                float cosTheta = 1 - 2*theta; // 0..1
                float sinTheta = sqrt(1.0 - cosTheta * cosTheta);
                // Local hemisphere direction (Z-up)
                vec3 localDir = vec3(sinTheta * cos(phi), sinTheta * sin(phi), cosTheta);
                
                // float cosTheta = float(i) / float(n_points - 1); // 0..1
                // float sinTheta = sqrt(1.0 - cosTheta * cosTheta);
                // float phi = golden_angle * float(i);

                // // Local hemisphere direction (Z-up)
                // vec3 localDir = vec3(sinTheta * cos(phi), sinTheta * sin(phi), cosTheta);

                // Rotate into world/view space using TBN
                vec3 rd = normalize(localDir.x * tangent + localDir.y * bitangent + localDir.z * n);
                if (dot(n,rd) < 0.0) {
                    rd *= -1.0;    
                }

                HitInfo h = getHit(ro, rd, false, prevt);
                // if (h.idx == selfidx) continue   ;
                nn++;
                if (h.idx == -2) {
                    retcolor += ((h.col * h.reflectiveness * (max(dot(n,rd),0.0))*0.8)/(1.0 + 0.005 * h.t*h.t));
                    return_color += retcolor;
                    break;
                    // return retcolor/ float(nn);
                }else if (h.idx == -1) {
                    retcolor += h.col * (1 - h.reflectiveness) * max(dot(n,rd),0.0);
                    return_color += retcolor;
                    break;
                }
                else {
                    reflectivity *= h.reflectiveness;
                    retcolor += h.col * (reflectivity) * max(dot(n,rd),0.0);
                    ro = ro + rd * h.t + h.normal * max(1e-4, h.t * 1e-5);
                }
                prevt = h.t;
            }
            // break;
        }

    // }

    return_color /= float(nn);
    return return_color;
}

vec4 trace_ray(vec3 ro, vec3 rd, int numreflect, ivec2 sampl, ivec2 pixel) {
    // int numreflections = 2;
    float prevrefl = 1.0;
    vec4 final_color = vec4(0,0,0,1);
    float l = 0;
    float prevt = -10.0;
    for (int j = 0; j<numreflect; j++){
        HitInfo h = getHit(ro, rd, false, prevt);
        
        vec3 intersectpoint = ro + rd * h.t;
        // for(int i = 0; i<light.length()/7; i++){
        //     vec3 point_light = vec3(light[i*7 + 0], light[i*7 + 1], light[i*7 + 2]);
        //     float h.reflectiveness = light[i*7 + 3];
        //     vec3 light_color = vec3(light[i*7 + 4], light[i*7 + 5], light[i*7 + 6]);
        //     point_light = (view * vec4(point_light, 1.0)).xyz; // Transform point light to view space
    
        // }
            vec3 interpoint = intersectpoint +  h.normal * epsilon;
            
            vec4 diffuseContrib = (1.0 - h.reflectiveness) * h.col;
            if (h.hit){
                diffuseContrib *= diffuse(interpoint, h.normal, h.idx, sampl, pixel, 5);
            }
            
            vec4 localcol = diffuseContrib;
            
            if (h.idx == -2){
        // final_color = vec4(1);
        // break;
                final_color += prevrefl*clamp(h.col * h.reflectiveness / h.t, 0.0, 1.0);
            }else {
                final_color += prevrefl*clamp(vec4(localcol.rgb,1.0), 0.0, 1.0);
            }
        rd = rd - 2*(dot(rd,h.normal))*h.normal;
        l += length(ro-intersectpoint);
        ro = intersectpoint +  h.normal * epsilon;
        
        prevrefl *= h.reflectiveness;
        if (!h.hit || h.idx == -2){
            break;
        }

        prevt = h.t;
    }

    final_color /= numreflect;
    return final_color;
}

void main() {
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    if (pixel.x >= int(u_resolution.x) || pixel.y >= int(u_resolution.y)) return;

    int nsamples = 2;

    vec4 final_color = vec4(0,0,0,1);

    ground = normalize((view * vec4(ground + ground_point, 1.0)).xyz); // Transform ground normal to view space
    ground_point = (view * vec4(ground_point, 1.0)).xyz; // Transform ground point to view space
    ground -= ground_point;
    
    ground = normalize(ground); // Normalize the ground normal

    for (int samplx = 0; samplx<nsamples; samplx++){
        for (int samply = 0; samply<nsamples; samply++){

            vec2 uv = (vec2(pixel.x+(samplx-nsamples/2)/2.0, pixel.y+(samply-nsamples/2)/2.0) + 0.5) / u_resolution * 2.0 - 1.0;
            // uv.x += samplx/10;
            uv.y = -uv.y; // flip

            float z = -1.0 / tan(radians(fov) * 0.5);
            vec3 rd = normalize((invView * vec4(vec3(uv, z), 0.0)).xyz);
            vec3 ro = (invView * vec4(vec3(0,0,0), 1.0)).xyz;


            // Ray direction in NDC
            int numreflections = 2;

            final_color += trace_ray(ro,rd,numreflections, ivec2(samplx*5, samply*5), pixel);
        }
    }

    final_color /= nsamples*nsamples;
    // final_color = vec4(1);
    imageStore(imgOutput, pixel, final_color);
    
}
